language: ruby
rvm:
- 2.1
cache: bundler
script: ./scripts/travis.sh
after_script: ./scripts/continua11y.sh
env:
    global:
    - RUN_SCRIPT="bundle exec jekyll serve --detach"
    - KILL_SCRIPT="pkill -f jekyll"
    - USE_SITEMAP=false